### PR TITLE
fix-43: make num_store_threads as  'signed long int'  

### PR DESCRIPTION
**Pull request by rajubairishetti**
Add getSigned() method in conf.cpp to get the 'signed long int' value. If user configures negative value to this property then scribe will starts with single writer thread for that category

### CODE REVIEW

**Comment by rajubairishetti** [comment]
@satish-mittal  could you  please review?

**Comment by satish-mittal** [comment]
Why do we need this fix? Even today, there are so many integer configs which are read as unsigned int. We should handle num_store_threads in a similar way.

**Comment by rajubairishetti** [comment]
Looks like, we are not handling for the other integer/long configs. If we specify negative value it takes the corresponding positive value. This would crash the system as it may spawn huge number of threads.

**Comment by satish-mittal** [comment]
The process can still crash if user provides a very large positive value. So we are not preventing scribe crash in all cases. This setting has to be configured carefully (set non-negative, low value), like other configs.

**Comment by rajubairishetti** [comment]
Yes. That will depend on the system configuration. Should we keep a limit on the max value of num_store_threads? I don't think this will be a good idea to keep a limit on the value.

**Comment by rajubairishetti** [comment]
Closing this pull req as even today it is not handling negative values of integer/long config properties. System behavior will be undefined if user provides negative value. Ex: num_thrift_server_threads

**Pull request closed without merging**
